/**
 * PDF Export API
 *
 * POST /api/export - Generate PDF from a research plan
 * GET  /api/export?p=<projectId> - Generate PDF from a saved project
 */

import { NextRequest, NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'
import { getProject } from '@/lib/projects'

interface PlanData {
  userQuestion: string
  businessDecision: string
  researchObjective: string
  recommendedMethods: Array<{
    name: string
    isPrimary: boolean
    rationale: string
  }>
  implementation: {
    questionProSteps: string
    sampleSize: string
    timeline: string
  }
  expectedOutputs: string
  decisionSupport: string
  assumptions: string[]
  caveats: string[]
}

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/#{1,6}\s*/g, '')
    .replace(/`/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim()
}

function generatePDF(plan: PlanData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 55, right: 55 },
      info: {
        Title: `Research Plan - ${plan.userQuestion.substring(0, 60)}`,
        Author: 'ResearchGuide by QuestionPro',
        Creator: 'ResearchGuide',
      }
    })

    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const pageWidth = doc.page.width - 55 - 55
    const black = '#1A1A1A'
    const gray = '#666666'
    const lightGray = '#F5F5F5'
    const accentColor = '#2563EB'

    // --- Header ---
    doc.rect(0, 0, doc.page.width, 100).fill('#1A1A1A')
    doc.fontSize(22).fill('#FFFFFF').font('Helvetica-Bold')
      .text('RESEARCH PLAN', 55, 30, { width: pageWidth })
    doc.fontSize(9).fill('#AAAAAA').font('Helvetica')
      .text('Generated by ResearchGuide | QuestionPro', 55, 60, { width: pageWidth })
    doc.fontSize(8).fill('#AAAAAA')
      .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 55, 75, { width: pageWidth })

    doc.y = 120

    // --- Research Question ---
    doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
      .text('RESEARCH QUESTION', 55, doc.y, { width: pageWidth })
    doc.moveDown(0.3)
    doc.fontSize(13).fill(black).font('Helvetica-Bold')
      .text(plan.userQuestion, 55, doc.y, { width: pageWidth })
    doc.moveDown(1.2)

    // --- Divider helper ---
    const drawDivider = () => {
      doc.moveTo(55, doc.y).lineTo(55 + pageWidth, doc.y).strokeColor('#E0E0E0').lineWidth(0.5).stroke()
      doc.moveDown(0.8)
    }

    // --- Business Decision ---
    if (plan.businessDecision) {
      drawDivider()
      doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
        .text('WHAT YOU\'RE TRYING TO DECIDE', 55, doc.y, { width: pageWidth })
      doc.moveDown(0.3)
      doc.fontSize(10).fill(black).font('Helvetica')
        .text(stripMarkdown(plan.businessDecision), 55, doc.y, { width: pageWidth })
      doc.moveDown(1)
    }

    // --- Research Objective ---
    if (plan.researchObjective) {
      drawDivider()
      doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
        .text('RESEARCH OBJECTIVE', 55, doc.y, { width: pageWidth })
      doc.moveDown(0.3)
      doc.fontSize(10).fill(black).font('Helvetica')
        .text(stripMarkdown(plan.researchObjective), 55, doc.y, { width: pageWidth })
      doc.moveDown(1)
    }

    // --- Recommended Methods ---
    if (plan.recommendedMethods && plan.recommendedMethods.length > 0) {
      drawDivider()
      doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
        .text('RECOMMENDED METHODOLOGY', 55, doc.y, { width: pageWidth })
      doc.moveDown(0.5)

      plan.recommendedMethods.forEach((method) => {
        const label = method.isPrimary ? 'PRIMARY' : 'SUPPORTING'
        const methodName = stripMarkdown(method.name)

        doc.fontSize(10).fill(black).font('Helvetica-Bold')
          .text(`[${label}] ${methodName}`, 65, doc.y, { width: pageWidth - 10 })

        if (method.rationale) {
          doc.moveDown(0.2)
          doc.fontSize(9).fill(gray).font('Helvetica')
            .text(stripMarkdown(method.rationale), 75, doc.y, { width: pageWidth - 20 })
        }
        doc.moveDown(0.7)
      })
      doc.moveDown(0.3)
    }

    // --- Implementation ---
    drawDivider()
    doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
      .text('IMPLEMENTATION', 55, doc.y, { width: pageWidth })
    doc.moveDown(0.5)

    // Sample size and timeline boxes
    if (plan.implementation.sampleSize || plan.implementation.timeline) {
      const boxY = doc.y
      const boxWidth = (pageWidth - 15) / 2

      doc.rect(55, boxY, boxWidth, 40).fill(lightGray)
      doc.fontSize(7).fill(gray).font('Helvetica-Bold')
        .text('SAMPLE SIZE', 65, boxY + 8, { width: boxWidth - 20 })
      doc.fontSize(10).fill(black).font('Helvetica-Bold')
        .text(plan.implementation.sampleSize || 'N/A', 65, boxY + 22, { width: boxWidth - 20 })

      doc.rect(55 + boxWidth + 15, boxY, boxWidth, 40).fill(lightGray)
      doc.fontSize(7).fill(gray).font('Helvetica-Bold')
        .text('TIMELINE', 65 + boxWidth + 15, boxY + 8, { width: boxWidth - 20 })
      doc.fontSize(10).fill(black).font('Helvetica-Bold')
        .text(plan.implementation.timeline || 'N/A', 65 + boxWidth + 15, boxY + 22, { width: boxWidth - 20 })

      doc.y = boxY + 55
    }

    if (plan.implementation.questionProSteps) {
      doc.fontSize(9).fill(black).font('Helvetica')
        .text(stripMarkdown(plan.implementation.questionProSteps), 55, doc.y, { width: pageWidth })
      doc.moveDown(1)
    }

    // --- Expected Outputs ---
    if (plan.expectedOutputs) {
      // Check if we need a new page
      if (doc.y > 650) doc.addPage()
      drawDivider()
      doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
        .text('EXPECTED OUTPUTS', 55, doc.y, { width: pageWidth })
      doc.moveDown(0.3)
      doc.fontSize(10).fill(black).font('Helvetica')
        .text(stripMarkdown(plan.expectedOutputs), 55, doc.y, { width: pageWidth })
      doc.moveDown(1)
    }

    // --- Decision Support ---
    if (plan.decisionSupport) {
      if (doc.y > 650) doc.addPage()
      drawDivider()
      doc.fontSize(11).fill(accentColor).font('Helvetica-Bold')
        .text('DECISION SUPPORT', 55, doc.y, { width: pageWidth })
      doc.moveDown(0.3)
      doc.fontSize(10).fill(black).font('Helvetica')
        .text(stripMarkdown(plan.decisionSupport), 55, doc.y, { width: pageWidth })
      doc.moveDown(1)
    }

    // --- Assumptions & Caveats ---
    if ((plan.assumptions && plan.assumptions.length > 0) || (plan.caveats && plan.caveats.length > 0)) {
      if (doc.y > 600) doc.addPage()
      drawDivider()

      const colWidth = (pageWidth - 15) / 2

      const startY = doc.y
      doc.fontSize(10).fill(accentColor).font('Helvetica-Bold')
        .text('ASSUMPTIONS', 55, startY, { width: colWidth })
      doc.moveDown(0.3)

      let leftY = doc.y
      if (plan.assumptions) {
        plan.assumptions.forEach(a => {
          doc.fontSize(8.5).fill(black).font('Helvetica')
            .text(`- ${stripMarkdown(a)}`, 55, leftY, { width: colWidth })
          leftY = doc.y + 4
        })
      }

      doc.fontSize(10).fill(accentColor).font('Helvetica-Bold')
        .text('CAVEATS', 55 + colWidth + 15, startY, { width: colWidth })

      let rightY = startY + 16
      if (plan.caveats) {
        plan.caveats.forEach(c => {
          doc.fontSize(8.5).fill(black).font('Helvetica')
            .text(`- ${stripMarkdown(c)}`, 55 + colWidth + 15, rightY, { width: colWidth })
          rightY = doc.y + 4
        })
      }

      doc.y = Math.max(leftY, rightY) + 10
    }

    // --- Footer ---
    doc.moveDown(2)
    doc.moveTo(55, doc.y).lineTo(55 + pageWidth, doc.y).strokeColor('#1A1A1A').lineWidth(1).stroke()
    doc.moveDown(0.5)
    doc.fontSize(8).fill(gray).font('Helvetica')
      .text('Generated by ResearchGuide | Powered by QuestionPro', 55, doc.y, {
        width: pageWidth,
        align: 'center'
      })
    doc.fontSize(7).fill(gray)
      .text('researchguide.up.railway.app', 55, doc.y + 12, {
        width: pageWidth,
        align: 'center'
      })

    doc.end()
  })
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    if (!body.plan) {
      return NextResponse.json({ error: 'Missing plan data' }, { status: 400 })
    }

    const pdfBuffer = await generatePDF(body.plan)

    return new Response(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="research-plan.pdf"',
        'Content-Length': pdfBuffer.length.toString(),
      }
    })
  } catch (error) {
    console.error('[Export API] PDF generation error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  try {
    const projectId = request.nextUrl.searchParams.get('p')

    if (!projectId) {
      return NextResponse.json({ error: 'Missing project ID' }, { status: 400 })
    }

    const project = await getProject(projectId)
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    const pdfBuffer = await generatePDF(project.plan as PlanData)

    return new Response(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="research-plan-${projectId}.pdf"`,
        'Content-Length': pdfBuffer.length.toString(),
      }
    })
  } catch (error) {
    console.error('[Export API] PDF generation error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}
