/**
 * PDF Export API - using jsPDF (pure JS, no native dependencies)
 *
 * POST /api/export - Generate PDF from a research plan
 */

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { jsPDF } from 'jspdf'

interface PlanData {
  userQuestion: string
  businessDecision: string
  researchObjective: string
  recommendedMethods: Array<{
    name: string
    isPrimary: boolean
    rationale: string
  }>
  implementation: {
    questionProSteps: string
    sampleSize: string
    timeline: string
  }
  expectedOutputs: string
  decisionSupport: string
  assumptions: string[]
  caveats: string[]
}

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/#{1,6}\s*/g, '')
    .replace(/`/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim()
}

function generatePDF(plan: PlanData): ArrayBuffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = 0

  const black = '#1A1A1A'
  const gray = '#666666'
  const accent = '#2563EB'
  const white = '#FFFFFF'

  // --- Header bar ---
  doc.setFillColor(26, 26, 26)
  doc.rect(0, 0, pageWidth, 35, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(white)
  doc.text('RESEARCH PLAN', margin, 15)
  doc.setFontSize(8)
  doc.setTextColor('#AAAAAA')
  doc.text('Generated by ResearchGuide | QuestionPro', margin, 22)
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin, 28)

  y = 45

  // --- Helper: section heading ---
  const drawHeading = (title: string) => {
    if (y > 260) { doc.addPage(); y = 20 }
    doc.setDrawColor('#E0E0E0')
    doc.setLineWidth(0.3)
    doc.line(margin, y, margin + contentWidth, y)
    y += 6
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(accent)
    doc.text(title, margin, y)
    y += 5
  }

  // --- Helper: body text with wrapping ---
  const drawBody = (text: string, fontSize = 9) => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(fontSize)
    doc.setTextColor(black)
    const lines = doc.splitTextToSize(stripMarkdown(text), contentWidth)
    for (const line of lines) {
      if (y > 275) { doc.addPage(); y = 20 }
      doc.text(line, margin, y)
      y += fontSize * 0.45
    }
    y += 3
  }

  // --- Research Question ---
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(accent)
  doc.text('RESEARCH QUESTION', margin, y)
  y += 5
  doc.setFontSize(12)
  doc.setTextColor(black)
  const qLines = doc.splitTextToSize(plan.userQuestion, contentWidth)
  for (const line of qLines) {
    doc.text(line, margin, y)
    y += 6
  }
  y += 5

  // --- Business Decision ---
  if (plan.businessDecision) {
    drawHeading("WHAT YOU'RE TRYING TO DECIDE")
    drawBody(plan.businessDecision)
  }

  // --- Research Objective ---
  if (plan.researchObjective) {
    drawHeading('RESEARCH OBJECTIVE')
    drawBody(plan.researchObjective)
  }

  // --- Recommended Methods ---
  if (plan.recommendedMethods && plan.recommendedMethods.length > 0) {
    drawHeading('RECOMMENDED METHODOLOGY')
    plan.recommendedMethods.forEach((method) => {
      if (y > 265) { doc.addPage(); y = 20 }
      const label = method.isPrimary ? 'PRIMARY' : 'SUPPORTING'
      const methodName = stripMarkdown(method.name)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(black)
      doc.text(`[${label}] ${methodName}`, margin + 3, y)
      y += 4
      if (method.rationale) {
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(8)
        doc.setTextColor(gray)
        const rLines = doc.splitTextToSize(stripMarkdown(method.rationale), contentWidth - 10)
        for (const line of rLines) {
          if (y > 275) { doc.addPage(); y = 20 }
          doc.text(line, margin + 6, y)
          y += 3.5
        }
      }
      y += 3
    })
  }

  // --- Implementation ---
  drawHeading('IMPLEMENTATION')

  // Sample size & timeline boxes
  if (plan.implementation.sampleSize || plan.implementation.timeline) {
    const boxWidth = (contentWidth - 5) / 2
    doc.setFillColor('#F5F5F5')
    doc.rect(margin, y - 1, boxWidth, 16, 'F')
    doc.rect(margin + boxWidth + 5, y - 1, boxWidth, 16, 'F')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(gray)
    doc.text('SAMPLE SIZE', margin + 3, y + 4)
    doc.text('TIMELINE', margin + boxWidth + 8, y + 4)

    doc.setFontSize(10)
    doc.setTextColor(black)
    doc.text(plan.implementation.sampleSize || 'N/A', margin + 3, y + 11)
    doc.text(plan.implementation.timeline || 'N/A', margin + boxWidth + 8, y + 11)
    y += 22
  }

  if (plan.implementation.questionProSteps) {
    drawBody(plan.implementation.questionProSteps, 8)
  }

  // --- Expected Outputs ---
  if (plan.expectedOutputs) {
    drawHeading('EXPECTED OUTPUTS')
    drawBody(plan.expectedOutputs)
  }

  // --- Decision Support ---
  if (plan.decisionSupport) {
    drawHeading('DECISION SUPPORT')
    drawBody(plan.decisionSupport)
  }

  // --- Assumptions & Caveats ---
  if ((plan.assumptions?.length > 0) || (plan.caveats?.length > 0)) {
    drawHeading('ASSUMPTIONS & CAVEATS')
    const colWidth = (contentWidth - 5) / 2

    if (plan.assumptions?.length > 0) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(accent)
      doc.text('Assumptions', margin, y)
      y += 4
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(black)
      plan.assumptions.forEach(a => {
        if (y > 275) { doc.addPage(); y = 20 }
        const aLines = doc.splitTextToSize(`- ${stripMarkdown(a)}`, colWidth)
        aLines.forEach((line: string) => { doc.text(line, margin, y); y += 3.5 })
      })
      y += 3
    }

    if (plan.caveats?.length > 0) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(accent)
      doc.text('Caveats', margin, y)
      y += 4
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(black)
      plan.caveats.forEach(c => {
        if (y > 275) { doc.addPage(); y = 20 }
        const cLines = doc.splitTextToSize(`- ${stripMarkdown(c)}`, colWidth)
        cLines.forEach((line: string) => { doc.text(line, margin, y); y += 3.5 })
      })
    }
  }

  // --- Footer ---
  if (y > 265) { doc.addPage(); y = 20 }
  y += 8
  doc.setDrawColor(black)
  doc.setLineWidth(0.5)
  doc.line(margin, y, margin + contentWidth, y)
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(gray)
  doc.text('Generated by ResearchGuide | Powered by QuestionPro', pageWidth / 2, y, { align: 'center' })
  doc.text('researchguide.up.railway.app', pageWidth / 2, y + 4, { align: 'center' })

  return doc.output('arraybuffer')
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    if (!body.plan) {
      return NextResponse.json({ error: 'Missing plan data' }, { status: 400 })
    }

    const pdfBuffer = generatePDF(body.plan)

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="research-plan.pdf"',
      }
    })
  } catch (error) {
    console.error('[Export API] PDF generation error:', error)
    return NextResponse.json({
      error: 'Failed to generate PDF',
      details: error instanceof Error ? error.message : String(error),
    }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  return NextResponse.json({ error: 'Use POST with plan data' }, { status: 400 })
}
