/**
 * PDF Export API - using jsPDF (pure JS, no native dependencies)
 *
 * POST /api/export - Generate PDF from a research plan
 */

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { jsPDF } from 'jspdf'

interface PlanData {
  userQuestion: string
  businessDecision: string
  researchObjective: string
  recommendedMethods: Array<{
    name: string
    isPrimary: boolean
    rationale: string
  }>
  implementation: {
    questionProSteps: string
    sampleSize: string
    timeline: string
  }
  expectedOutputs: string
  decisionSupport: string
  assumptions: string[]
  caveats: string[]
}

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/#{1,6}\s*/g, '')
    .replace(/`/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim()
}

function generatePDF(plan: PlanData): ArrayBuffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = 0

  const black = '#1A1A1A'
  const darkGray = '#444444'
  const gray = '#666666'
  const lightGray = '#999999'
  const accent = '#2563EB'
  const white = '#FFFFFF'

  // --- Page footer helper ---
  const drawPageFooter = () => {
    doc.setDrawColor('#E0E0E0')
    doc.setLineWidth(0.3)
    doc.line(margin, pageHeight - 12, margin + contentWidth, pageHeight - 12)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.5)
    doc.setTextColor(lightGray)
    doc.text('CONFIDENTIAL - Generated by ResearchGuide | QuestionPro', margin, pageHeight - 8)
    doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }), margin + contentWidth, pageHeight - 8, { align: 'right' })
  }

  // --- Cover area ---
  doc.setFillColor(26, 26, 26)
  doc.rect(0, 0, pageWidth, 50, 'F')
  // Blue accent line
  doc.setFillColor(37, 99, 235)
  doc.rect(margin, 42, 30, 1.5, 'F')
  // Title text
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(white)
  doc.text('Research Plan', margin, 18)
  doc.setFontSize(8)
  doc.setTextColor('#AAAAAA')
  doc.text('QuestionPro  |  ResearchGuide', margin, 26)
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin, 33)
  doc.setFontSize(7)
  doc.setTextColor('#777777')
  doc.text('CONFIDENTIAL', margin + contentWidth, 33, { align: 'right' })

  y = 58

  // --- Helper: section heading with accent bar ---
  const drawHeading = (title: string) => {
    if (y > 255) { drawPageFooter(); doc.addPage(); y = 20 }
    y += 4
    // Accent bar
    doc.setFillColor(37, 99, 235)
    doc.rect(margin, y - 1, 1.5, 6, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(black)
    doc.text(title, margin + 5, y + 3.5)
    y += 10
  }

  // --- Helper: body text with wrapping ---
  const drawBody = (text: string, fontSize = 9, indent = 0) => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(fontSize)
    doc.setTextColor(darkGray)
    const lines = doc.splitTextToSize(stripMarkdown(text), contentWidth - indent)
    for (const line of lines) {
      if (y > 270) { drawPageFooter(); doc.addPage(); y = 20 }
      doc.text(line, margin + indent, y)
      y += fontSize * 0.48
    }
    y += 3
  }

  // --- Research Question ---
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(black)
  const qLines = doc.splitTextToSize('"' + plan.userQuestion + '"', contentWidth)
  for (const line of qLines) {
    if (y > 270) { drawPageFooter(); doc.addPage(); y = 20 }
    doc.text(line, margin, y)
    y += 6.5
  }
  y += 6

  // --- Business Decision ---
  if (plan.businessDecision) {
    drawHeading('Business Decision')
    drawBody(plan.businessDecision)
  }

  // --- Research Objective ---
  if (plan.researchObjective) {
    drawHeading('Research Objective')
    drawBody(plan.researchObjective)
  }

  // --- Recommended Methods ---
  if (plan.recommendedMethods && plan.recommendedMethods.length > 0) {
    drawHeading('Recommended Methodology')
    plan.recommendedMethods.forEach((method, idx) => {
      if (y > 260) { drawPageFooter(); doc.addPage(); y = 20 }
      const label = method.isPrimary ? 'PRIMARY' : 'SUPPORTING'
      const methodName = stripMarkdown(method.name)

      // Method label badge
      doc.setFillColor(method.isPrimary ? 37 : 200, method.isPrimary ? 99 : 200, method.isPrimary ? 235 : 200)
      const labelWidth = doc.getStringUnitWidth(label) * 6.5 / doc.internal.scaleFactor + 4
      doc.rect(margin, y - 2.5, labelWidth, 4, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(6.5)
      doc.setTextColor(method.isPrimary ? white : '#555555')
      doc.text(label, margin + 2, y)

      // Method name
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9.5)
      doc.setTextColor(black)
      doc.text(methodName, margin + labelWidth + 3, y)
      y += 5

      if (method.rationale) {
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(8)
        doc.setTextColor(gray)
        const rLines = doc.splitTextToSize(stripMarkdown(method.rationale), contentWidth - 4)
        for (const line of rLines) {
          if (y > 270) { drawPageFooter(); doc.addPage(); y = 20 }
          doc.text(line, margin + 4, y)
          y += 3.8
        }
      }
      y += 4
    })
  }

  // --- Implementation ---
  drawHeading('Implementation')

  // Sample size & timeline in styled boxes
  if (plan.implementation.sampleSize || plan.implementation.timeline) {
    const boxWidth = (contentWidth - 6) / 2
    // Box 1 - Sample Size
    doc.setFillColor(245, 247, 250)
    doc.rect(margin, y - 2, boxWidth, 18, 'F')
    doc.setDrawColor('#E0E0E0')
    doc.setLineWidth(0.3)
    doc.rect(margin, y - 2, boxWidth, 18, 'S')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(lightGray)
    doc.text('SAMPLE SIZE', margin + 4, y + 3)
    doc.setFontSize(11)
    doc.setTextColor(black)
    doc.text(plan.implementation.sampleSize || 'N/A', margin + 4, y + 11)

    // Box 2 - Timeline
    const box2X = margin + boxWidth + 6
    doc.setFillColor(245, 247, 250)
    doc.rect(box2X, y - 2, boxWidth, 18, 'F')
    doc.setDrawColor('#E0E0E0')
    doc.rect(box2X, y - 2, boxWidth, 18, 'S')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(lightGray)
    doc.text('TIMELINE', box2X + 4, y + 3)
    doc.setFontSize(11)
    doc.setTextColor(black)
    doc.text(plan.implementation.timeline || 'N/A', box2X + 4, y + 11)
    y += 24
  }

  if (plan.implementation.questionProSteps) {
    drawBody(plan.implementation.questionProSteps, 8.5, 2)
  }

  // --- Expected Outputs ---
  if (plan.expectedOutputs) {
    drawHeading('Expected Outputs')
    drawBody(plan.expectedOutputs)
  }

  // --- Decision Support ---
  if (plan.decisionSupport) {
    drawHeading('Decision Support')
    drawBody(plan.decisionSupport)
  }

  // --- Assumptions & Caveats side by side ---
  if ((plan.assumptions?.length > 0) || (plan.caveats?.length > 0)) {
    drawHeading('Assumptions & Caveats')
    const colWidth = (contentWidth - 8) / 2

    const startY = y
    let leftY = y
    let rightY = y

    // Left column - Assumptions
    if (plan.assumptions?.length > 0) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(accent)
      doc.text('Assumptions', margin, leftY)
      leftY += 5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(darkGray)
      plan.assumptions.forEach(a => {
        if (leftY > 270) { drawPageFooter(); doc.addPage(); leftY = 20; rightY = 20 }
        const aLines = doc.splitTextToSize('- ' + stripMarkdown(a), colWidth)
        aLines.forEach((line: string) => { doc.text(line, margin, leftY); leftY += 3.8 })
        leftY += 1
      })
    }

    // Right column - Caveats
    if (plan.caveats?.length > 0) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(accent)
      doc.text('Caveats', margin + colWidth + 8, rightY)
      rightY += 5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(darkGray)
      plan.caveats.forEach(c => {
        if (rightY > 270) { drawPageFooter(); doc.addPage(); rightY = 20 }
        const cLines = doc.splitTextToSize('- ' + stripMarkdown(c), colWidth)
        cLines.forEach((line: string) => { doc.text(line, margin + colWidth + 8, rightY); rightY += 3.8 })
        rightY += 1
      })
    }

    y = Math.max(leftY, rightY) + 3
  }

  // --- Footer on last page ---
  drawPageFooter()

  return doc.output('arraybuffer')
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    if (!body.plan) {
      return NextResponse.json({ error: 'Missing plan data' }, { status: 400 })
    }

    const pdfBuffer = generatePDF(body.plan)

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="research-plan.pdf"',
      }
    })
  } catch (error) {
    console.error('[Export API] PDF generation error:', error)
    return NextResponse.json({
      error: 'Failed to generate PDF',
      details: error instanceof Error ? error.message : String(error),
    }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  return NextResponse.json({ error: 'Use POST with plan data' }, { status: 400 })
}
